# Generated by Django 2.1.1 on 2018-09-04 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalUpdater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('webservice_uri', models.CharField(blank=True, max_length=400, null=True)),
                ('webservice_login', models.CharField(blank=True, max_length=100, null=True)),
                ('webservice_password_plaintext', models.CharField(blank=True, max_length=100, null=True)),
                ('webservice_token', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(help_text='Enter memorable short name', max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('purchase_date', models.DateField(help_text='Enter the earliest date money was invested')),
                ('liquidate_date', models.DateField(blank=True, help_text='Enter the date the Asset was liquidated', null=True)),
                ('investment_type', models.CharField(choices=[('Prop', 'Real Estate'), ('Cash', 'Cash Investment/Term Deposit'), ('Stck', 'Stocks or Shares'), ('Bond', 'Bonds'), ('Fund', 'Funds'), ('Comp', 'Direct company shareholding'), ('Othr', 'Other')], help_text='Enter the broad category of investment', max_length=4)),
                ('currency', models.CharField(max_length=3)),
                ('external_identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('external_updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investmentrecorder.ExternalUpdater')),
            ],
            options={
                'ordering': ['investment_type', 'short_name'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentCapital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(help_text='Enter the date this tranche of investment was made')),
                ('liquidate_date', models.DateField(help_text='Enter the date this tranche of investment was made', null=True)),
                ('purchase_amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('liquidate_amount', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investmentrecorder.Investment')),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Enter the date the revenue was received')),
                ('currency', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investmentrecorder.Investment')),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentRevenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Enter the date the revenue was received')),
                ('currency', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investmentrecorder.Investment')),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentValuation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Enter the date the revenue was received')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('status', models.CharField(help_text='Actual or derived interim value', max_length=10)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investmentrecorder.Investment')),
            ],
        ),
    ]
