# Generated by Django 2.1.1 on 2018-09-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investmentrecorder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='total_invested',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='total_number_of_units',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=17, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='total_returned',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='investmentcapital',
            name='number_of_units',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=17, null=True),
        ),
        migrations.AddField(
            model_name='investmentcapital',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='investmentvaluation',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='investmentcapital',
            name='liquidate_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='investmentcapital',
            name='liquidate_date',
            field=models.DateField(blank=True, help_text='Enter the date this tranche of investment was liquidated', null=True),
        ),
        migrations.AlterField(
            model_name='investmentcapital',
            name='purchase_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='investmentcapital',
            name='purchase_date',
            field=models.DateField(blank=True, help_text='Enter the date this tranche of investment was made', null=True),
        ),
    ]
