# Generated by Django 2.1.1 on 2018-09-04 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investmentrecorder', '0002_auto_20180904_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(max_length=3)),
                ('symbol', models.CharField(max_length=1)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='investment',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investmentrecorder.Currency'),
        ),
        migrations.AlterField(
            model_name='investmentcapital',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investmentrecorder.Currency'),
        ),
        migrations.AlterField(
            model_name='investmentexpense',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investmentrecorder.Currency'),
        ),
        migrations.AlterField(
            model_name='investmentrevenue',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investmentrecorder.Currency'),
        ),
    ]
