# Generated by Django 2.1.1 on 2018-09-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investmentrecorder', '0004_auto_20180905_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentexpense',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='investmentexpense',
            name='investment',
        ),
        migrations.RemoveField(
            model_name='investmentrevenue',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='investmentrevenue',
            name='investment',
        ),
        migrations.RemoveField(
            model_name='investmenttransaction',
            name='boughtsold',
        ),
        migrations.AddField(
            model_name='investmenttransaction',
            name='description',
            field=models.CharField(blank=True, help_text='Please enter a useful description', max_length=500),
        ),
        migrations.AddField(
            model_name='investmenttransaction',
            name='type',
            field=models.CharField(choices=[('b', 'Bought'), ('s', 'Sold'), ('r', 'Revenue'), ('e', 'Expense')], default='b', max_length=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='InvestmentExpense',
        ),
        migrations.DeleteModel(
            name='InvestmentRevenue',
        ),
    ]
